apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: docker
  name: docker
spec:
  containers:
  - image: docker:dind
    name: docker
    volumeMounts:
    - name: docker
      mountPath: /var/run/docker.sock
    resources: {}
    securityContext:
      privileged: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: docker        
    hostPath:
      path: /var/run/docker.sock
status: {}
