apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: docker
  name: docker
spec:
  containers:
  - image: docker
    name: docker
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
